name: 'Fetch data'

on:
  workflow_dispatch:
  push:
    branches:
      - cpany

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: dev
          path: ./main
      - uses: ./main
        with:
          skipClean: main
